version: "3.8"

services:
 web:
  build: .
  volumes:
   - .:/app
  ports:
   - 8000:8000
  image: app:django
  container_name: django_container
  command: python manage.py runserver 0.0.0.0:8000
  env_file:
   - .env
  depends_on:
   - db
   - elasticsearch
 db:
  image: postgres
  env_file: .env
  container_name: postgres_db
  restart: always
  ports:
   - 5432:5432
  volumes:
   - postgres_data:/var/lib/postgresql/data/
 elasticsearch:
  image: elasticsearch:8.16.3
  env_file: .env
  container_name: elasticsearch_container
  ports:
    - "9200:9200"
  environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
  restart: always
  volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
adminer:
  env_file: .env
  image: adminer
  restart: always
  ports:
   - 3333:8080
volumes:
 postgres_data:
 elasticsearch_data: