# Generated by Django 5.0.1 on 2025-03-04 13:22

from django.db import migrations


def load_initial_data(apps, schema_editor):
    # Get the models (we need to get them from the apps registry, not import directly)
    MealType = apps.get_model('website', 'MealType')
    CuisineType = apps.get_model('website', 'CuisineType')
    DietType = apps.get_model('website', 'DietType')
    IntoleranceType = apps.get_model('website', 'IntoleranceType')

    # Create MealTypes
    meal_types = ["Main course", "Side dish", "Dessert", "Appetizer",
                  "Salad", "Bread", "Breakfast", "Soup", "Beverage", "Sauce", "Marinade", "Fingerfood"]
    for meal in meal_types:
        MealType.objects.create(name=meal)

    # Create CuisineTypes
    cuisine_types = ["African", "Asian", "American", "British", "Cajun", "Caribbean", "Chinese",
                     "Eastern European", "European", "French", "German", "Greek", "Indian", "Irish", "Italian",
                     "Japanese", "Jewish", "Korean", "Latin American", "Mediterranean", "Mexican", "Middle Eastern",
                     "Nordic", "Southern", "Spanish", "Thai", "Vietnamese"]
    for cuisine in cuisine_types:
        CuisineType.objects.create(name=cuisine)

    # Create DietTypes
    diet_types = ["Gluten Free", "Ketogenic", "Vegetarian", "Lacto-Vegetarian",
                  "Ovo-Vegetarian", "Vegan", "Pescetarian", "Paleo", "Primal", "Low FODMAP", "Whole30"]

    for diet in diet_types:
        DietType.objects.create(name=diet)

    # Create IntoleranceTypes
    intolerance_types = ["Dairy", "Egg", "Gluten", "Grain", "Peanut",
                         "Seafood", "Sesame", "Shellfish", "Soy", "Sulfite", "Tree Nut", "Wheat"]
    for intolerance in intolerance_types:
        IntoleranceType.objects.create(name=intolerance)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
